// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rodrigocavalhero/nanojira/internal/email (interfaces: Sender)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_email.go -package=mocks github.com/rodrigocavalhero/nanojira/internal/email Sender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	email "github.com/rodrigocavalhero/nanojira/internal/email"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendAssignmentNotification mocks base method.
func (m *MockSender) SendAssignmentNotification(ctx context.Context, arg1 email.AssignmentEmail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAssignmentNotification", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAssignmentNotification indicates an expected call of SendAssignmentNotification.
func (mr *MockSenderMockRecorder) SendAssignmentNotification(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAssignmentNotification", reflect.TypeOf((*MockSender)(nil).SendAssignmentNotification), ctx, arg1)
}
