// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rodrigocavalhero/nanojira/internal/repository (interfaces: UserRepository,TaskRepository,StepBackRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_repository.go -package=mocks github.com/rodrigocavalhero/nanojira/internal/repository UserRepository,TaskRepository,StepBackRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodrigocavalhero/nanojira/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockTaskRepository) Count(ctx context.Context, filter domain.TaskFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTaskRepositoryMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTaskRepository)(nil).Count), ctx, filter)
}

// Create mocks base method.
func (m *MockTaskRepository) Create(ctx context.Context, task *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), ctx, task)
}

// CreateAssignmentNotification mocks base method.
func (m *MockTaskRepository) CreateAssignmentNotification(ctx context.Context, n *domain.AssignmentNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssignmentNotification", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAssignmentNotification indicates an expected call of CreateAssignmentNotification.
func (mr *MockTaskRepositoryMockRecorder) CreateAssignmentNotification(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssignmentNotification", reflect.TypeOf((*MockTaskRepository)(nil).CreateAssignmentNotification), ctx, n)
}

// GetByID mocks base method.
func (m *MockTaskRepository) GetByID(ctx context.Context, id string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTaskRepository) List(ctx context.Context, filter domain.TaskFilter) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepository)(nil).List), ctx, filter)
}

// ListAssignmentNotifications mocks base method.
func (m *MockTaskRepository) ListAssignmentNotifications(ctx context.Context, taskID string) ([]domain.AssignmentNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssignmentNotifications", ctx, taskID)
	ret0, _ := ret[0].([]domain.AssignmentNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssignmentNotifications indicates an expected call of ListAssignmentNotifications.
func (mr *MockTaskRepositoryMockRecorder) ListAssignmentNotifications(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssignmentNotifications", reflect.TypeOf((*MockTaskRepository)(nil).ListAssignmentNotifications), ctx, taskID)
}

// Update mocks base method.
func (m *MockTaskRepository) Update(ctx context.Context, task *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepositoryMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepository)(nil).Update), ctx, task)
}

// MockStepBackRepository is a mock of StepBackRepository interface.
type MockStepBackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStepBackRepositoryMockRecorder
	isgomock struct{}
}

// MockStepBackRepositoryMockRecorder is the mock recorder for MockStepBackRepository.
type MockStepBackRepositoryMockRecorder struct {
	mock *MockStepBackRepository
}

// NewMockStepBackRepository creates a new mock instance.
func NewMockStepBackRepository(ctrl *gomock.Controller) *MockStepBackRepository {
	mock := &MockStepBackRepository{ctrl: ctrl}
	mock.recorder = &MockStepBackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepBackRepository) EXPECT() *MockStepBackRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStepBackRepository) Create(ctx context.Context, req *domain.StepBackRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStepBackRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStepBackRepository)(nil).Create), ctx, req)
}

// GetByID mocks base method.
func (m *MockStepBackRepository) GetByID(ctx context.Context, id string) (*domain.StepBackRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.StepBackRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStepBackRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStepBackRepository)(nil).GetByID), ctx, id)
}

// GetPendingByTaskID mocks base method.
func (m *MockStepBackRepository) GetPendingByTaskID(ctx context.Context, taskID string) (*domain.StepBackRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByTaskID", ctx, taskID)
	ret0, _ := ret[0].(*domain.StepBackRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByTaskID indicates an expected call of GetPendingByTaskID.
func (mr *MockStepBackRepositoryMockRecorder) GetPendingByTaskID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByTaskID", reflect.TypeOf((*MockStepBackRepository)(nil).GetPendingByTaskID), ctx, taskID)
}

// Update mocks base method.
func (m *MockStepBackRepository) Update(ctx context.Context, req *domain.StepBackRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStepBackRepositoryMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStepBackRepository)(nil).Update), ctx, req)
}
